name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Set up JDK 11
        uses: actions/setup-java@v1.4.1
        with:
          java-version: 11
      - name: Build with Gradle for Java 11
        run: ./gradlew build
      - name: Publish to Maven Central
        env:
          MAVEN_CENTRAL_LOGIN: ${{ secrets.MAVEN_CENTRAL_LOGIN }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
        run: ./gradlew publish
